## Posttest 7
### Muhammad Basith Algiffari
### 2009106071

Mengimport library yang diperlukan

In [14]:
import tensorflow as tf
import numpy as np

membuat variabel random_tensor menggunakan fungsi tensorflow yaitu random.normal() dan prime_tensor yang merupakan list berisi bilangan prima yang di convert ke tensorflow menggunakan fungsi convert_to_tensor()

In [16]:
random_tensor = tf.random.normal(shape=[5,5])
random_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.60956943, -2.539072  , -0.36086676, -0.09337256,  1.8954229 ],
       [-0.48581547,  0.8314311 ,  0.12846115, -0.15661429,  0.938417  ],
       [ 1.2420084 , -0.12758482,  0.05109114, -1.0636181 , -1.667379  ],
       [ 0.33053935, -0.26773483,  1.4997106 ,  0.06089767,  0.56461537],
       [ 1.2150694 ,  0.03344109, -0.49372026,  1.297015  , -1.8034872 ]],
      dtype=float32)>

In [17]:
list_tensor = [[2, 3, 5, 7, 11], [13, 17, 19, 23, 29],
                [31, 37, 41, 43, 47], [53, 59, 61, 67, 71],
                [73, 79, 83, 89, 97]]
prime_tensor = tf.convert_to_tensor(list_tensor, dtype=tf.float32)
prime_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]], dtype=float32)>

### Arithmetic Operations on Tensors
melakukan operasi aritmatika dalam tensor flow

### Menggunakan fungsi add/penjumlahan

In [18]:
print(tf.add(random_tensor, prime_tensor))

tf.Tensor(
[[ 1.3904306   0.46092796  4.6391335   6.9066277  12.895423  ]
 [12.514185   17.83143    19.128462   22.843386   29.938417  ]
 [32.24201    36.872414   41.05109    41.936382   45.332623  ]
 [53.33054    58.732265   62.49971    67.0609     71.56461   ]
 [74.21507    79.03344    82.50628    90.29701    95.19651   ]], shape=(5, 5), dtype=float32)


### Menggunakan fungsi subtract/pengurangan

In [19]:
print(tf.subtract(random_tensor, prime_tensor))

tf.Tensor(
[[ -2.6095695  -5.539072   -5.3608665  -7.0933723  -9.104577 ]
 [-13.485815  -16.16857   -18.871538  -23.156614  -28.061583 ]
 [-29.757992  -37.127586  -40.94891   -44.063618  -48.667377 ]
 [-52.66946   -59.267735  -59.50029   -66.9391    -70.43539  ]
 [-71.78493   -78.96656   -83.49372   -87.70299   -98.80349  ]], shape=(5, 5), dtype=float32)


### Menggunakan fungsi multiply/perkalian

In [20]:
print(tf.multiply(random_tensor, prime_tensor))

tf.Tensor(
[[  -1.2191389   -7.617216    -1.8043338   -0.6536079   20.849651 ]
 [  -6.315601    14.134329     2.4407618   -3.6021287   27.214094 ]
 [  38.502262    -4.7206383    2.0947368  -45.735577   -78.36681  ]
 [  17.518585   -15.796354    91.482346     4.0801444   40.087692 ]
 [  88.700066     2.6418457  -40.978783   115.43433   -174.93826  ]], shape=(5, 5), dtype=float32)


### Menggunakan fungsi matmul/perhitungan secara matrix

In [21]:
print(tf.matmul(random_tensor, prime_tensor))

tf.Tensor(
[[  88.00318    85.88443    85.53863    84.25377    79.92748 ]
 [  74.023155   82.324646   86.97016    94.271996  104.71204 ]
 [-175.68118  -191.02896  -197.39249  -211.70262  -224.88924 ]
 [  88.11605   100.12699   108.63171   114.97434   125.44945 ]
 [ -75.353226  -80.00555   -84.103325  -85.565704  -91.71949 ]], shape=(5, 5), dtype=float32)


### Menggunakan fungsi argmax/mencari nilai terbesar dan argmin/ mencari nilai terkecil

In [23]:
print(random_tensor)
max_tensor = tf.argmax(random_tensor, axis=0)
min_tensor = tf.argmin(random_tensor, axis=1)
print("Lokasi value terbesar adalah ",max_tensor.numpy())
print("Lokasi value terkecil adalah ",min_tensor.numpy())

tf.Tensor(
[[-0.60956943 -2.539072   -0.36086676 -0.09337256  1.8954229 ]
 [-0.48581547  0.8314311   0.12846115 -0.15661429  0.938417  ]
 [ 1.2420084  -0.12758482  0.05109114 -1.0636181  -1.667379  ]
 [ 0.33053935 -0.26773483  1.4997106   0.06089767  0.56461537]
 [ 1.2150694   0.03344109 -0.49372026  1.297015   -1.8034872 ]], shape=(5, 5), dtype=float32)
Lokasi value terbesar adalah  [2 1 3 4 0]
Lokasi value terkecil adalah  [1 0 4 1 4]


Melakukan penggabungan variabel random_tensor dan prime_tensor menggunakan fungsi concat

In [27]:
concat_tensor = tf.concat([random_tensor, prime_tensor], axis=0)
print(concat_tensor)

tf.Tensor(
[[-6.0956943e-01 -2.5390720e+00 -3.6086676e-01 -9.3372561e-02
   1.8954229e+00]
 [-4.8581547e-01  8.3143109e-01  1.2846115e-01 -1.5661429e-01
   9.3841702e-01]
 [ 1.2420084e+00 -1.2758482e-01  5.1091142e-02 -1.0636181e+00
  -1.6673790e+00]
 [ 3.3053935e-01 -2.6773483e-01  1.4997106e+00  6.0897674e-02
   5.6461537e-01]
 [ 1.2150694e+00  3.3441085e-02 -4.9372026e-01  1.2970150e+00
  -1.8034872e+00]
 [ 2.0000000e+00  3.0000000e+00  5.0000000e+00  7.0000000e+00
   1.1000000e+01]
 [ 1.3000000e+01  1.7000000e+01  1.9000000e+01  2.3000000e+01
   2.9000000e+01]
 [ 3.1000000e+01  3.7000000e+01  4.1000000e+01  4.3000000e+01
   4.7000000e+01]
 [ 5.3000000e+01  5.9000000e+01  6.1000000e+01  6.7000000e+01
   7.1000000e+01]
 [ 7.3000000e+01  7.9000000e+01  8.3000000e+01  8.9000000e+01
   9.7000000e+01]], shape=(10, 5), dtype=float32)


Membuat variabel yang mengsorting/mengurutkan data random_tensor dan prime_tensor secara Descending

In [28]:
sort_random_tensor = tf.sort(random_tensor, direction="DESCENDING")
sort_prime_tensor = tf.sort(prime_tensor, direction="DESCENDING")

Menampilkan hasil sorting variabel random_tensor dan prime_tensor

In [31]:
print(sort_random_tensor)
print(sort_prime_tensor)

tf.Tensor(
[[ 1.8954229  -0.09337256 -0.36086676 -0.60956943 -2.539072  ]
 [ 0.938417    0.8314311   0.12846115 -0.15661429 -0.48581547]
 [ 1.2420084   0.05109114 -0.12758482 -1.0636181  -1.667379  ]
 [ 1.4997106   0.56461537  0.33053935  0.06089767 -0.26773483]
 [ 1.297015    1.2150694   0.03344109 -0.49372026 -1.8034872 ]], shape=(5, 5), dtype=float32)
tf.Tensor(
[[11.  7.  5.  3.  2.]
 [29. 23. 19. 17. 13.]
 [47. 43. 41. 37. 31.]
 [71. 67. 61. 59. 53.]
 [97. 89. 83. 79. 73.]], shape=(5, 5), dtype=float32)
